-- The lifecycle state of a generated occurrence (M2, jlogicsoftware/prudent#56, ADR-039).
--
-- Occurrences so far (V20260929090000) held only WHEN. This adds WHAT BECAME OF IT: planned,
-- completed or skipped. "Overdue" is deliberately not a value here -- it is a planned occurrence
-- whose date has passed in its plan's time zone, worked out at read time, so there is no job to
-- miss and no stale row to find.
--
-- THIS FILE IS IMMUTABLE ONCE APPLIED, INCLUDING ITS COMMENTS (see V20260817090000__prudent_init).

-- Deliberately NOT a Postgres ENUM type and NOT a CHECK, for the reason the init migration gives
-- for prudent_account.kind: the vocabulary is the application's to decide. The DEFAULT is what
-- every occurrence generated before this migration, and every one generated by the writer that
-- names no state, is: not yet resolved.
ALTER TABLE prudent_plan_occurrence
    ADD COLUMN state TEXT NOT NULL DEFAULT 'PLANNED';

-- The two views read a user's open occurrences by date; the state leads so a user's completed and
-- skipped history is not walked to find the few still planned.
CREATE INDEX prudent_plan_occurrence_open_idx
    ON prudent_plan_occurrence (user_id, state, occurrence_date);
