/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/apple-app-site-association": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Apple App Site Association */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/assetlinks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Links */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's accounts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListAccountsResponse"];
                        "application/x-protobuf": components["schemas"]["ListAccountsResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create an account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountRequest"];
                    "application/x-protobuf": components["schemas"]["CreateAccountRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                        "application/x-protobuf": components["schemas"]["Account"];
                    };
                };
                /** @description A blank name, an unspecified type, or an empty/duplicate/unknown currency set */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                        "application/x-protobuf": components["schemas"]["Account"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
            };
        };
        /** Replace an account */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAccountRequest"];
                    "application/x-protobuf": components["schemas"]["UpdateAccountRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                        "application/x-protobuf": components["schemas"]["Account"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description The update drops a currency that still has records */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an account */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description The account still has records */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users for the admin panel (paginated via the Content-Range convention) */
        get: {
            parameters: {
                query?: {
                    /** @description ra-data-simple-rest range, JSON [start,end] inclusive, e.g. [0,24] */
                    range?: string;
                    /** @description ra-data-simple-rest sort, JSON [field,order], e.g. ["email","ASC"] */
                    sort?: string;
                    /** @description ra-data-simple-rest filter, JSON object; supports role and q (email) */
                    filter?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of users; total row count in the Content-Range header */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUserList"];
                    };
                };
                /** @description No active session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Session lacks the admin role */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single user by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The user record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"];
                        "application/x-protobuf": components["schemas"]["AdminUser"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No user with that id (ZenError) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a user's editable fields */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                    "application/x-protobuf": components["schemas"]["AdminUser"];
                };
            };
            responses: {
                /** @description The updated user record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"];
                        "application/x-protobuf": components["schemas"]["AdminUser"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No user with that id (ZenError) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/spend-by-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spend by category, in one currency, for a year or one month of it
         * @description Query parameters: currency (required, ISO-4217), year (required), month (optional, 1-12 — a single month; omitted means the whole year).
         */
        get: {
            parameters: {
                query?: {
                    currency?: string;
                    month?: number;
                    year?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpendByCategoryResponse"];
                        "application/x-protobuf": components["schemas"]["SpendByCategoryResponse"];
                    };
                };
                /** @description A missing/invalid currency, a missing year, or an out-of-range month */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/spend-by-period": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spend by period, in one currency, over a trailing window of buckets
         * @description Query parameters: currency (required, ISO-4217), granularity (required, MONTH or YEAR), count (required, 1-60 — the number of trailing buckets, ending at the current period resolved in UTC).
         */
        get: {
            parameters: {
                query?: {
                    count?: number;
                    currency?: string;
                    granularity?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpendByPeriodResponse"];
                        "application/x-protobuf": components["schemas"]["SpendByPeriodResponse"];
                    };
                };
                /** @description A missing/invalid currency, granularity, or an out-of-range count */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current identity, or 204 when anonymous */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The authenticated identity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity"];
                        "application/x-protobuf": components["schemas"]["Identity"];
                    };
                };
                /** @description No active session */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "application/x-protobuf": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated; session cookies set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity"];
                        "application/x-protobuf": components["schemas"]["Identity"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Terminate the current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    zen_access_token?: string;
                };
            };
            requestBody?: never;
            responses: {
                /** @description Session cookies cleared */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password for the current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    zen_access_token?: string;
                };
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetPasswordRequest"];
                    "application/x-protobuf": components["schemas"]["SetPasswordRequest"];
                };
            };
            responses: {
                /** @description Password changed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No active session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange the refresh-token cookie for a fresh session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    zen_refresh_token?: string;
                };
            };
            requestBody?: never;
            responses: {
                /** @description Refreshed; new session cookies set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity"];
                        "application/x-protobuf": components["schemas"]["Identity"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new identity with email and password */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Accept-Language"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "application/x-protobuf": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Registered and signed in (Supabase auto-confirms); session cookies set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity"];
                        "application/x-protobuf": components["schemas"]["Identity"];
                    };
                };
                /** @description Registered, email confirmation required: account created, no session yet. The returned Identity has email_verified=false; the caller shows a "check your email" state. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity"];
                        "application/x-protobuf": components["schemas"]["Identity"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/restore-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger the password-recovery email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RestorePasswordRequest"];
                    "application/x-protobuf": components["schemas"]["RestorePasswordRequest"];
                };
            };
            responses: {
                /** @description Recovery email dispatched if the address exists */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange the tokens from a Supabase email link for a cookie session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SessionExchangeRequest"];
                    "application/x-protobuf": components["schemas"]["SessionExchangeRequest"];
                };
            };
            responses: {
                /** @description Link accepted; session cookies set */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Identity"];
                        "application/x-protobuf": components["schemas"]["Identity"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The link is invalid or expired */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's categories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every category owned by the caller */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListCategoriesResponse"];
                        "application/x-protobuf": components["schemas"]["ListCategoriesResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a category */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCategoryRequest"];
                    "application/x-protobuf": components["schemas"]["CreateCategoryRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                        "application/x-protobuf": components["schemas"]["Category"];
                    };
                };
                /** @description A blank title, or an icon_key the client cannot render */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one category */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                        "application/x-protobuf": components["schemas"]["Category"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No such category for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
            };
        };
        /** Replace a category */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCategoryRequest"];
                    "application/x-protobuf": components["schemas"]["UpdateCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                        "application/x-protobuf": components["schemas"]["Category"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a category */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description The category still has records */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                        "application/x-protobuf": components["schemas"]["HealthStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run every scheduled job that is currently due */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Shared secret identifying the external scheduler */
                    "X-Zen-Job-Token"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The tick result: what was due and what happened to it */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobTickResult"];
                        "application/x-protobuf": components["schemas"]["JobTickResult"];
                    };
                };
                /** @description Missing or invalid trigger credential (ZenError) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's records */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListRecordsResponse"];
                        "application/x-protobuf": components["schemas"]["ListRecordsResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a record */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRecordRequest"];
                    "application/x-protobuf": components["schemas"]["CreateRecordRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Record"];
                        "application/x-protobuf": components["schemas"]["Record"];
                    };
                };
                /** @description A blank title, a malformed date, an account or category that is not the caller's, or a currency the account does not hold */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Record"];
                        "application/x-protobuf": components["schemas"]["Record"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
            };
        };
        /** Replace a record */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRecordRequest"];
                    "application/x-protobuf": components["schemas"]["UpdateRecordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Record"];
                        "application/x-protobuf": components["schemas"]["Record"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a record */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the authenticated user's settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                        "application/x-protobuf": components["schemas"]["Settings"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Replace the authenticated user's settings */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSettingsRequest"];
                    "application/x-protobuf": components["schemas"]["UpdateSettingsRequest"];
                };
            };
            responses: {
                /** @description The settings AS STORED, which may differ from what was sent if a default was substituted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                        "application/x-protobuf": components["schemas"]["Settings"];
                    };
                };
                /** @description A non-empty main_currency that is not an ISO-4217 code */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZenError"];
                        "application/x-protobuf": components["schemas"]["ZenError"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Landing */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Liveness/readiness payload returned by GET /api/v1/health. */
        HealthStatus: {
            /** @description Overall status, e.g. "ok". */
            status?: string;
            /** @description Logical service name. */
            service?: string;
            /**
             * Format: int64
             * @description Server wall-clock time in ms since the Unix epoch.
             */
            timestampMs?: string;
        };
        /** @description The error body every Prudent endpoint returns in place of a response on any status >= 400. There is no envelope: HTTP status carries the status, X-Request-ID carries the request id, and this carries the error. A client parses it with the same codec it would a success, because the transport seam serialises it in the negotiated format. */
        ZenError: {
            /** @description The stable machine-readable code a client branches on — "not_found", "invalid", "conflict", or one of the framework's own ("unauthorized"). This is API; the message is not. */
            code?: string;
            /** @description Human-readable detail, for a log or a developer console. Not for branching. */
            message?: string;
        };
        /** @description The authenticated identity returned by the framework's auth endpoints (zen-identity's AuthResource, whose paths are scanned into this document from the framework jar). An Identity with an empty id denotes "no session". */
        Identity: {
            /** @description Stable identity id (the Supabase auth.users id / JWT sub). */
            id?: string;
            /** @description One of "pending", "active", "revoked", "disabled". */
            lifecycleState?: string;
            /** @description Optional human-readable reason for the current lifecycle state. */
            lifecycleReason?: string;
            /** @description Authority roles loaded from the users table, never from the JWT. */
            roles?: string[];
            capabilities?: string[];
            /**
             * Format: int64
             * @description Creation time in ms since the Unix epoch.
             */
            createdAtMs?: number;
            emailVerified?: boolean;
        };
        /** @description Body for POST /api/v1/auth/login. */
        LoginRequest: {
            email?: string;
            password?: string;
        };
        /** @description Body for POST /api/v1/auth/register. */
        RegisterRequest: {
            email?: string;
            password?: string;
            /** @description Optional. Where the confirmation link returns the user; empty means the server's default. Accepted only on an EXACT match with a configured target — an unchecked return address would let anyone have a live session token mailed to a destination they control. */
            redirectUri?: string;
        };
        /** @description Body for POST /api/v1/auth/restore-password. */
        RestorePasswordRequest: {
            email?: string;
            /** @description Optional; validated exactly as RegisterRequest.redirectUri. */
            redirectUri?: string;
        };
        /** @description Body for POST /api/v1/auth/session. The tokens a Supabase email link left in the URL fragment, posted back by the client so the backend can validate them and set cookies. */
        SessionExchangeRequest: {
            accessToken?: string;
            /** @description Optional; without it the session cannot be refreshed silently. */
            refreshToken?: string;
        };
        /** @description Body for POST /api/v1/auth/password; sets a new password for the current session. */
        SetPasswordRequest: {
            password?: string;
        };
        /** @description A users-table row projected for the admin panel (GET/PUT /api/v1/admin/users). Prudent has no admin panel until Phase 5; the schema is here because the framework's AdminUserResource ships its PATHS and they are scanned into this document regardless. */
        AdminUser: {
            id?: string;
            email?: string;
            displayName?: string;
            nickname?: string;
            /** @description Authority role; one of "user", "admin", "reviewer", "b2b_admin". */
            role?: string;
            /** @description Preferred language code. For Prudent this is one of en, uk, pl — and it is the SOLE locale source for email, which has no request to read Accept-Language from. */
            language?: string;
            isPremium?: boolean;
            isPrivate?: boolean;
            emailVerified?: boolean;
            /** Format: int64 */
            createdAtMs?: number;
            /**
             * Format: int64
             * @description Last login time in ms since the Unix epoch; 0 when never logged in.
             */
            lastLoginAtMs?: number;
        };
        /** @description GET /api/v1/admin/users response; a page of AdminUser records as a bare JSON array. The total row count travels in the Content-Range header (the ra-data-simple-rest convention). */
        AdminUserList: components["schemas"]["AdminUser"][];
        /** @description The outcome of one job executed during a tick of POST /api/v1/jobs/trigger. */
        JobRun: {
            jobId?: string;
            /** @description Terminal status of the run; "success" or "failure". */
            status?: string;
            /** Format: int64 */
            startedAtMs?: number;
            /** Format: int64 */
            durationMs?: number;
            /** @description Failure detail; empty on success. */
            error?: string;
        };
        /** @description POST /api/v1/jobs/trigger response. Prudent does not assemble zen-jobs today, so nothing serves this path — but the schema is declared because the reference is scanned in from the framework, and a $ref with no component behind it is a dangling reference in a document Prudent publishes. */
        JobTickResult: {
            /** Format: int64 */
            startedAtMs?: number;
            /** Format: int32 */
            due?: number;
            /** Format: int32 */
            succeeded?: number;
            /** Format: int32 */
            failed?: number;
            skippedOverlap?: boolean;
            runs?: components["schemas"]["JobRun"][];
        };
        /** @description A spending category, as the server holds it. */
        Category: {
            /**
             * Format: uuid
             * @description Server-minted. A create request carries no id.
             */
            id?: string;
            title?: string;
            /**
             * @description A STABLE KEY, never an icon code point — "work", "leisure", "food", "restaurant", "medicine". A code point would defeat Flutter's icon tree-shaking, shipping the whole Material font in every bundle. Validated server-side; an unknown key is rejected on write, and a client renders a documented fallback for one it does not know.
             * @enum {string}
             */
            iconKey?: "work" | "leisure" | "food" | "restaurant" | "medicine";
            description?: string;
            /**
             * Format: int32
             * @description The category colour as unsigned 0xAARRGGBB. A colour is a value and ARGB is its portable form, so it survives a user picking outside the shipped palette.
             */
            colorArgb?: number;
        };
        /** @description Body for POST /api/v1/categories. No id field — the server mints it. */
        CreateCategoryRequest: {
            title?: string;
            /** @enum {string} */
            iconKey?: "work" | "leisure" | "food" | "restaurant" | "medicine";
            description?: string;
            /** Format: int32 */
            colorArgb?: number;
        };
        /** @description Body for PUT /api/v1/categories/{id}. A FULL REPLACEMENT, not a patch: every mutable field is applied, so a field the client omits is written as its proto3 default. Plain proto3 scalars have no presence, so an absent field and an explicitly-sent default are identical on the wire — a merge would have to guess which it received. */
        UpdateCategoryRequest: {
            title?: string;
            /** @enum {string} */
            iconKey?: "work" | "leisure" | "food" | "restaurant" | "medicine";
            description?: string;
            /** Format: int32 */
            colorArgb?: number;
        };
        /** @description GET /api/v1/categories — every category owned by the caller. */
        ListCategoriesResponse: {
            categories?: components["schemas"]["Category"][];
        };
        /**
         * @description What kind of account this is. ACCOUNT_TYPE_UNSPECIFIED is what proto3 decodes an omitted field to and is REJECTED server-side — defaulting it to cash would make "the client forgot" indistinguishable from "the client meant cash", and cash is a valid answer.
         * @enum {string}
         */
        AccountType: "ACCOUNT_TYPE_UNSPECIFIED" | "ACCOUNT_TYPE_CASH" | "ACCOUNT_TYPE_CARD" | "ACCOUNT_TYPE_CHECKING" | "ACCOUNT_TYPE_SAVINGS";
        /** @description One currency an account holds, and how much of it. */
        CurrencyBalance: {
            /** @description ISO-4217 alphabetic code, validated server-side against the JDK's table. */
            currency?: string;
            /**
             * Format: int64
             * @description An INTEGER COUNT OF MINOR UNITS — "1234" is 12.34 PLN — never a float. Binary floating point cannot represent 0.10 and an expense tracker sums thousands of values. Note the type: proto3 canonical JSON encodes int64 AS A STRING, while the Protobuf binary mode carries a number; the two must agree after decoding.
             */
            amountMinor?: string;
        };
        /** @description An account, as the server holds it. AN ACCOUNT HOLDS SEVERAL CURRENCIES AT ONCE, each with its own balance. There is no FX: the balances are independent, nothing converts between them, and summing across them is refused rather than done at a rate nobody chose. */
        Account: {
            /** Format: uuid */
            id?: string;
            name?: string;
            type?: components["schemas"]["AccountType"];
            /** @description The account offered first when creating a record. Exactly one per user is true; the server clears the flag on the previous holder rather than trusting the client to. */
            isDefault?: boolean;
            /** @description An inactive account is kept for its history rather than deleted. */
            isActive?: boolean;
            includeInTotal?: boolean;
            /** @description Two flags rather than one: a savings account a user wants visible but excluded from spendable funds needs them to differ. */
            includeInOverview?: boolean;
            /** @description The currencies this account holds, one entry each, in the order the server stores them. NEVER EMPTY and at most one entry per currency — both rejected server-side. The set is DECLARED rather than inferred, which is what lets the server reject a record in a currency the account does not hold instead of silently opening a new balance. */
            balances?: components["schemas"]["CurrencyBalance"][];
        };
        /** @description Body for POST /api/v1/accounts. No id field — the server mints it. */
        CreateAccountRequest: {
            name?: string;
            type?: components["schemas"]["AccountType"];
            isDefault?: boolean;
            isActive?: boolean;
            includeInTotal?: boolean;
            includeInOverview?: boolean;
            balances?: components["schemas"]["CurrencyBalance"][];
        };
        /**
         * @description Body for PUT /api/v1/accounts/{id}. A FULL REPLACEMENT — an entry omitted from `balances` is an entry the client is asking to remove.
         *     TWO SERVER RULES THIS MESSAGE CANNOT EXPRESS, both refusals rather than best-effort repairs: a currency that still has records cannot be dropped (409 — it would orphan money that left an account no longer admitting it exists), and a currency code is never edited in place (there is no rename; dropping PLN and adding EUR is two operations, and the first rule catches the case where it would have reinterpreted 100 PLN as 100 EUR). Adding a currency is always allowed — that is how an account becomes multi-currency after the fact.
         */
        UpdateAccountRequest: {
            name?: string;
            type?: components["schemas"]["AccountType"];
            isDefault?: boolean;
            isActive?: boolean;
            includeInTotal?: boolean;
            includeInOverview?: boolean;
            balances?: components["schemas"]["CurrencyBalance"][];
        };
        /** @description GET /api/v1/accounts — every account owned by the caller. */
        ListAccountsResponse: {
            accounts?: components["schemas"]["Account"][];
        };
        /** @description A single transaction, as the server holds it. */
        Record: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /**
             * Format: int64
             * @description Minor units, exact under addition. See CurrencyBalance.amountMinor.
             */
            amountMinor?: string;
            /** @description Which of the owning account's currencies this record is denominated in. Client-supplied and required; the server REJECTS a currency the account does not hold. That refusal is what replaced inheritance when an account gained the ability to hold several currencies — a validation rule rather than an unsayable state, which is the price of the feature. */
            currency?: string;
            /**
             * Format: date
             * @description A CIVIL DATE, ISO-8601 YYYY-MM-DD — not an instant. A purchase happens on a calendar day; an epoch timestamp would force every reader to pick a timezone, and at a daylight-saving boundary a record would shift a day — at a month edge, into the wrong month, which is a wrong total.
             */
            date?: string;
            /** Format: uuid */
            categoryId?: string;
            /**
             * Format: uuid
             * @description REQUIRED. A record with no account is money that left no account, and a balance computed over such records is arithmetic with a hole in it.
             */
            accountId?: string;
        };
        /** @description Body for POST /api/v1/records. No id field — the server mints it. */
        CreateRecordRequest: {
            title?: string;
            /** Format: int64 */
            amountMinor?: string;
            /** Format: date */
            date?: string;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            accountId?: string;
            currency?: string;
        };
        /** @description Body for PUT /api/v1/records/{id}. A FULL REPLACEMENT. Moving a record between accounts and changing its currency are ONE operation and are validated together: the new currency must be one the NEW account holds. */
        UpdateRecordRequest: {
            title?: string;
            /** Format: int64 */
            amountMinor?: string;
            /** Format: date */
            date?: string;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            accountId?: string;
            currency?: string;
        };
        /** @description GET /api/v1/records — every record owned by the caller. UNPAGINATED IN v1, which is a decision rather than an oversight: a personal expense tracker's record list is bounded by one person's spending. When one gets long enough to need paging, the page parameters are query parameters on the GET and this message gains its page metadata — a backward-compatible addition. */
        ListRecordsResponse: {
            records?: components["schemas"]["Record"][];
        };
        /** @description The authenticated user's settings. A SINGLETON: there is no id, no create, no delete and no list, and the URL carries no id because the token is the entire addressing scheme. The row is created on first login, not by a client. */
        Settings: {
            /**
             * @description The user's main currency — A LABEL, NEVER A CONVERSION TARGET. It selects which currency a record form pre-selects, which per-currency total the overview shows first, and what an empty state names. It is never used to convert between currencies or to sum across them, because Prudent does no FX.
             *     NEVER EMPTY ON A RESPONSE: the server resolves the default before answering, so a GET always names a real currency. Not required to be a currency any of the user's accounts holds — it is a display preference.
             */
            mainCurrency?: string;
        };
        /**
         * @description The bucketing width for GET /api/v1/analytics/spend-by-period. GRANULARITY_UNSPECIFIED is what proto3 decodes an omitted field to and is REJECTED server-side, for the same reason ACCOUNT_TYPE_UNSPECIFIED is.
         * @enum {string}
         */
        Granularity: "GRANULARITY_UNSPECIFIED" | "GRANULARITY_MONTH" | "GRANULARITY_YEAR";
        /** @description One category's total spend (expense magnitude, never signed) within scope. */
        CategorySpend: {
            /** Format: uuid */
            categoryId?: string;
            /**
             * Format: int64
             * @description POSITIVE — the magnitude of expense in this category, in the response's currency.
             */
            amountMinor?: string;
        };
        /** @description GET /api/v1/analytics/spend-by-category. THE EMPTY CASE: a user with no expenses in scope gets `items` empty, never a CategorySpend with a zero amount standing in for "nothing spent" — those are different facts and must stay visually different. */
        SpendByCategoryResponse: {
            /** @description Echoes the request's currency. */
            currency?: string;
            items?: components["schemas"]["CategorySpend"][];
        };
        /** @description One period's total spend (expense magnitude, never signed). */
        PeriodSpend: {
            /** @description "yyyy-MM" for GRANULARITY_MONTH, "yyyy" for GRANULARITY_YEAR — sorts lexicographically in calendar order. Never a rendered month name; the client renders that from its own locale. */
            period?: string;
            /**
             * Format: int64
             * @description POSITIVE — the magnitude of expense in this period, in the response's currency.
             */
            amountMinor?: string;
        };
        /** @description GET /api/v1/analytics/spend-by-period. Buckets with no expenses are OMITTED, not returned with a zero amount, for the same empty-vs-zero reason as SpendByCategoryResponse. `periods` is ordered oldest to newest. */
        SpendByPeriodResponse: {
            currency?: string;
            granularity?: components["schemas"]["Granularity"];
            periods?: components["schemas"]["PeriodSpend"][];
        };
        /** @description Body for PUT /api/v1/settings. A FULL REPLACEMENT, and the response carries the resulting Settings rather than an empty body — the server may have substituted a default, and a client that has to re-read to learn what it just wrote is a round trip the response could have saved. */
        UpdateSettingsRequest: {
            /** @description AN EMPTY VALUE MEANS "RESET TO THE DEFAULT", not "leave unchanged". proto3 has no presence for a string, so "" and unset are the same bytes; one reading had to be chosen, and there is nothing else in this message that "leave unchanged" could preserve. When a second field lands here, that sentence stops being true. */
            mainCurrency?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
